spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/academico_db
    username: carrito_user
    password: carrito_pass
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    show-sql: true

server:
  port: 8080

token:
  validation:
    url: http://localhost:8082/users/validate-token

services:
  rabbitmq:
    url: http://localhost:9100/send-message
  kafka:
    url: http://localhost:8089/api/matricula/events